---
- hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: Install Mysql 8.0 dependencies
      apt:
        update_cache: yes
        name:
          - mysql-server-8.0
          - python3-mysqldb
        state: latest
      become: yes
    - name: 'Cria o banco de dados MySQL DB'
      mysql_db:
        name: "{{ wp_db_name }}"
        state: present
      become: yes

    - name: 'Cria usuário do MySQL DB'
      mysql_user:
        login_user: root
        name: "{{ wp_username }}"
        password: "{{ wp_user_pass }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - "{{ wp_host_ip }}"
      become: yes

    - name: 'Configura mysql para aceitar conexões remotas'
      copy:
        src: '/configs/mysqld.cnf'
        dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      become: yes
      notify:
        - restart mysql

- hosts: wordpress
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: Add PHP 7 PPA repository
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install PHP 7.3, Apache2 dependencies
      apt:
        update_cache: yes
        name:
          - php7.3
          - apache2
          - libapache2-mod-php7.3
          - php7.3-gd
          - libssh2-1
          - php7.3-ssh2
          - php7.3-mysql
          - php7.3-zip
          - python3-mysqldb
        state: latest
      become: yes

    - name: 'Faz download do wordpress'
      get_url:
        url: 'https://br.wordpress.org/latest-pt_BR.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: 'Descompacta o arquivo do wordpress tar gz'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes

    - name: 'Copia o arquivo de configuração do wordpress'
      copy:
        src: "{{ wp_installation_dir }}/wp-config-sample.php"
        dest: "{{ wp_installation_dir }}/wp-config.php"
        remote_src: yes
      become: yes

    - name: 'Edita o arquivo de configuração do wordpress para conectar ao banco MySQL'
      replace:
        path: "{{ wp_installation_dir }}/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'nome_do_banco_de_dados_aqui', value: "{{ wp_db_name }}"}
        - { regex: 'nome_de_usuario_aqui', value: "{{ wp_username }}"}
        - { regex: 'senha_aqui', value: "{{ wp_user_pass }}"}
        - { regex: 'localhost', value: "{{ wp_db_ip }}"}
      become: yes

    - name: 'Copia arquivo, Configura Apache para servir wordpress'
      template:
        src: '/configs/templates/000-default.conf.j2'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache
