---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependência do sistema operacial com php5'
      apt:
        name: ['php5', 'apache2', 'libapache2-mod-php5', 'php5-gd', 'libssh2-php', 'php5-mcrypt', 'mysql-server-5.6', 'python-mysqldb', 'php5-mysql']
        state: latest
      become: yes
      
    - name: 'Cria o banco de dados MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
