---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependência do sistema operacional com php5'
      apt:
        name: ['php5', 'apache2', 'libapache2-mod-php5', 'php5-gd', 'libssh2-php', 'php5-mcrypt', 'mysql-server-5.6', 'python-mysqldb', 'php5-mysql']
        state: latest
      become: yes

    - name: 'Cria o banco de dados MySQL DB'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present

    - name: 'Cria usuário do MySQL DB'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present
